server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devices
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        default_batch_fetch_size: 50
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
    level:
        org.springframework: INFO